apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskify-api
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "taskify-api-ip"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskify-api
                port:
                  number: 80
