apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - hpa.yml

commonLabels:
  app.kubernetes.io/name: taskify-api
  app.kubernetes.io/managed-by: kustomize
