apiVersion: v1
kind: Secret
metadata:
  name: taskify-secrets
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME"
  JWT_REFRESH_SECRET: "REPLACE_ME"
  CLOUDINARY_API_KEY: "REPLACE_ME"
  CLOUDINARY_API_SECRET: "REPLACE_ME"
