apiVersion: v1
kind: Service
metadata:
  name: taskify-api
  labels:
    app: taskify-api
spec:
  type: ClusterIP
  selector:
    app: taskify-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
