apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskify-staging

resources:
  - ../../base

patches:
  - path: configmap-patch.yml
  - target:
      kind: HorizontalPodAutoscaler
      name: taskify-api
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: Deployment
      name: taskify-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
